// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL1fuiNiwd7r8ZWN8b2tXbuZPi1ZVnb8s',
    appId: '1:486104934859:web:cc2bf1ee6553d4cb60ae4e',
    messagingSenderId: '486104934859',
    projectId: 'instagram-f2920',
    authDomain: 'instagram-f2920.firebaseapp.com',
    storageBucket: 'instagram-f2920.appspot.com',
    measurementId: 'G-CZBV2NXXYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgFkkgFy7QzjwBjfqYNwWwJusKErXdalo',
    appId: '1:486104934859:android:0303fec0137e14ef60ae4e',
    messagingSenderId: '486104934859',
    projectId: 'instagram-f2920',
    storageBucket: 'instagram-f2920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdz_f7tsb3M6SmhG8LF4Kihp4AaTOETo',
    appId: '1:486104934859:ios:fa1c5ea224cf230060ae4e',
    messagingSenderId: '486104934859',
    projectId: 'instagram-f2920',
    storageBucket: 'instagram-f2920.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdz_f7tsb3M6SmhG8LF4Kihp4AaTOETo',
    appId: '1:486104934859:ios:fa1c5ea224cf230060ae4e',
    messagingSenderId: '486104934859',
    projectId: 'instagram-f2920',
    storageBucket: 'instagram-f2920.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL1fuiNiwd7r8ZWN8b2tXbuZPi1ZVnb8s',
    appId: '1:486104934859:web:4bd569df4c69a76260ae4e',
    messagingSenderId: '486104934859',
    projectId: 'instagram-f2920',
    authDomain: 'instagram-f2920.firebaseapp.com',
    storageBucket: 'instagram-f2920.appspot.com',
    measurementId: 'G-465MP0RS8L',
  );
}
